version: "3.3"

services:

  dockernode:
    container_name: node-react-biblioteca
    build: .
    command: npm start
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    networks:
      - rede_node_express

networks:
  rede_node_express:
    driver: bridge